version: "3.9"
services:
  cloud-stroage-proxy:
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"
    environment:
      - "PORT=8080"
      - "SERVICE-API-KEY=86c5ceb27e1bf441130299c0209e5f35b88089f62c06b2b09d65772274f12057"